### ISSUE TITLE
SPAM controls

### ISSUE THREAD

**Issue by newton27** [boonex/trident#320] opened 2016-06-28 21:58 UTC
I cannot get any messages with attachments from any members, even turning off the spam controls won't allow them. I get emails with with normal messages that are being sent directly to spam filters to my email.

Still missing images all over, and now Persons and English modules will not update.

**Comment by AlexTr** [comment] 2016-06-29 00:55
Please could you describe in the details how to reproduce the problem ?

**Comment by newton27** [comment] 2016-06-29 02:17
I removed the spam module today, as I never got the attachments included. 
i.e. game saves of map, a simple file to download.
They get stripped from the message, I get an email to admin email saying it is spam with the message which clearly is the message with attached missing and tagged for spam.
All messages are tagged as spam. akismet in the antispam_block_log.

**Comment by AlexTr** [comment] 2016-06-30 00:43
Please could you specify what messages are marked as spam ? Some screenshots please ?

**Comment by newton27** [comment] 2016-06-30 14:47
All messages from members to each other. No matter the content of the message. If an attachment is included it is not delivered.

- Write message, add attachment of file

![attachment 1](https://cloud.githubusercontent.com/assets/4349640/16492413/b3d0cf94-3eaf-11e6-9867-96e1366f2a25.JPG)

- Message shows attachment
![attachment 2](https://cloud.githubusercontent.com/assets/4349640/16492449/d981110e-3eaf-11e6-83b1-aed78b682a18.JPG)


- Received message shows "box" no link to file.

![attachment 3](https://cloud.githubusercontent.com/assets/4349640/16492457/e2b8a8b8-3eaf-11e6-94df-3d8c2fcba135.JPG)


- Compose new message, the attachment is still in the selection box, no matter who is composing the message the attachment is there.
![missing image 4](https://cloud.githubusercontent.com/assets/4349640/16492485/fc67e404-3eaf-11e6-97f2-1125c25d3bc3.JPG)

**Comment by newton27** [comment] 2016-06-30 14:49
![attachment 5](https://cloud.githubusercontent.com/assets/4349640/16492572/4256b8fa-3eb0-11e6-8c16-c8040575cceb.JPG)

And my spam report of this message is now marked as spam.

**Comment by AlexTr** [comment] 2016-07-06 02:46
What is the type if the attached file ? it looks like it isn't image but used in image tag.

Please could specify your Antispam settings ?

**Comment by newton27** [comment] 2016-07-06 05:33
I had to remove the spam module

Michael Newton

boonexsupport.com

**Closed** 2016-07-06 06:26 UTC
Labels: question
