### ISSUE TITLE
Timeline: Textboxes prefilled

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#302] opened 2016-06-27 11:50 UTC
After submitting a timeline post and THEN refreshing the page the textbox is prefilled again with the sent content.

Also after submitting comments to timeline post the textbox for the comment is not getting empty.

**Comment by AntonLV** [comment] 2016-08-05 12:08
RE: _After submitting a timeline post and THEN refreshing the page the textbox is prefilled again with the sent content._
The issue was fixed. Also the same issue was fixed in Post Comment form on content pages like View Post.

RE: _Also after submitting comments to timeline post the textbox for the comment is not getting empty._
Cannot reproduce the issue.

**Closed by AntonLV** 2016-08-05 12:08 UTC
Labels: bug
